### ISSUE TITLE
turkish characters problem.

### ISSUE THREAD

**Issue by ArresT-AnarchY** [pupi1985/Q2A-Ultimate-SEO#2]
i use a sitemap splitter (that is coded by me) with external php  btw i tested that seo plugin. i dont see lang_string. i guess it moved to root.  

1 ) **there is turkish char problem in metas and sitemap url.** so i turned my code.
2 ) if anybody use background on q2a. i see problem about background style on plugins. so it is unimportant style problem. ;)

example i used

```
$tr = array('ş','Ş','ı','I','İ','ğ','Ğ','ü','Ü','ö','Ö','Ç','ç','(',')','/',':',',');
$eng = array('s','s','i','i','i','g','g','u','u','o','o','c','c','','','-','-','');
$s = str_replace($tr,$eng,$s);
```

thanks for ur interesting.

ps. if u want, i translate lang_string to turkish. show me lang file. i dont search because of time.

**Comment by pupi1985** [comment]
> there is turkish char problem in metas and sitemap url.
Please, let me know what the problem is and the steps to reproduce it. Bear in mind, I've know idea about Turkish characters.
> i see problem about background style on plugins
Idem.

BTW, this is not my plugin, I just use this fork to *selectively* fix some issues that are raised in the Q2A forum. I'm not planning on adding new features. If I understand the problem, can reproduce the problem and consider it is relatively simple to fix then I'll fix it. Otherwise, I will advise you to raise the issue to the plugin developer's repo: https://github.com/q2a-projects/Q2A-Ultimate-SEO

**Comment by ArresT-AnarchY** [comment]
i see. i thought you are resuming this plugin. (so sorry for that. :\ coz i survey ur plugins. they are successful. especially your text (xls bla bla) to database system is very success too.  i think you find a algorithm about content of seperate Q and A. Because if anybody have a big database to added mysql, it is very hard to seperate it in text files.i wrote it in q2a web site.) 

AND
i saw Turkish characters problem about that letter --->"Ü, Ğ, ö, Ö, Ç, ç etc." 
when a question used that letter, they ar showing metas (always) and sitemaps (sometimes) ---> "%10, %13, %12".

i think it is about utf problem.
 
style is not important. it can be solved by many people. 

Thanks for interest.

**Comment by pupi1985** [comment]
I enabled **Answer Content for Meta Description** and **Selected Answer Content for Meta Description**.

Added a question with content `şş` and answered that question with content `şşşşşşşşşşşşşşşşşşşşşşşş`.

I selected that question as best and gave it an upvote (to make sure I trigger the conditions for it to be put in the meta description HTML tag). This is what I see:
![image](https://cloud.githubusercontent.com/assets/1449790/22399661/804049fc-e580-11e6-984d-73c94ddba424.png)

This seems to be a perfectly valid meta description.

**Comment by ArresT-AnarchY** [comment]
only i have problem ? 

![screenshot_8](https://cloud.githubusercontent.com/assets/6937143/22400389/f13b236c-e5bb-11e6-8017-c4e273a0cc9d.jpg)


![screenshot_6](https://cloud.githubusercontent.com/assets/6937143/22400394/1c70b84e-e5bc-11e6-91a9-e64c0212d54f.jpg)

**Comment by pupi1985** [comment]
The description meta looks perfectly fine in your example. The only one containing encoded characters is the URL, which should be encoded, is it is a URL. Please, refer to these docs for more information:
http://www.blooberry.com/indexdot/html/topics/urlencoding.htm
http://www.ietf.org/rfc/rfc1738.txt

**Comment by ArresT-AnarchY** [comment]
okey i will read and search. thanks for interest.
