### ISSUE TITLE
Sitemap generated by this plugin do not update automatically in the search console.

### ISSUE THREAD

**Issue by engrmdbelal** [pupi1985/q2a-ultimate-seo#4]
when I was using the previous version of Ultimate Seo Plugin, I used this plugin sitemap and it was updated regularly in the search console.But since I installed your updated plugin, my Sitemap Search Console has not been updated automatically. It has to be updated manually.

**Comment by engrmdbelal** [comment]
But I didn't have this problem when I was using the previous version. Sitemaps generated by the Ultimate seo plugin in the search console were automatically updated.

**Comment by pupi1985** [comment]
OK. Once you can clarify what the issue with the plugin is, please, let me know

**Comment by pupi1985** [comment]
I opened the last sitemap file. It contained a set of X questions. I asked a new question. I opened the last sitemap file. It contained X set of questions plus the newly created one. That proves the sitemap is being updated. If you can prove that wrong, please, go ahead, I'll be happy to fix the issue.

**Comment by engrmdbelal** [comment]
Please fix this problem for me privately. I am willing to pay you for this. Can you give me your WhatsApp number?
