### ISSUE TITLE
Found another problem.

### ISSUE THREAD

**Issue by engrmdbelal** [pupi1985/q2a-ultimate-seo#6]
Please visit the link and see the details.
https://www.question2answer.org/qa/96814/plz-someone-fix-this-error?show=96924#a96924

**Comment by pupi1985** [comment]
Please, don't duplicate here and in Q2A the bugs. Here is enough.

As a side note, don't feel bad about mentioning the issues you face. It's not my plugin, I'm just fixing it :sweat_smile:
