### ISSUE TITLE
Sitemap issue

### ISSUE THREAD

**Issue by mehedihassanpranto** [pupi1985/q2a-ultimate-seo#9]
This page contains the following errors:
error on line 5 at column 6: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.

**Comment by pupi1985** [comment]
I just took a look at your site and it looks good to me. If you face the issue again, please, let me know the steps to reproduce the issue in my development environment.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url>
		<loc>https://yoursite.com/....</loc>
		<priority>0.5</priority>
	</url>
</urlset>
```
